### ISSUE TITLE
Double charging

### ISSUE THREAD

**Issue by akhumdingers** [Auction-Sniper/sniping#1]
I paid for the service once and now it's trying to charge me again.

**Comment by Auction-Sniper** [comment]
How many computers are you trying to use it on?

**Comment by akhumdingers** [comment]
Just one.

**Comment by Auction-Sniper** [comment]
Did you uninstall or delete the app\folders?

**Comment by Auction-Sniper** [comment]
Or have windows firewall enabled blocking the activation port usually it
gives a message when you start the app and gives 2 options to allow or
block?

**Comment by akhumdingers** [comment]
Didn't uninstall or delete anything, and it only gives an "Unhandled Error" pop up on start up.

**Comment by Auction-Sniper** [comment]
That's the issue the unhandled error what does that unhandled error say?

**Comment by akhumdingers** [comment]
Unhandled Error
Error: listen EADDRINUSE: address already in use 127.0.0.1:54645
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_uvExceptionWithHostPort (node:internal/errors:589:12)
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at doListen (node:net:1937:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Auction-Sniper** [comment]
Ok that is the error that prevented your license from being activated...
can you please try rebooting your computer to free up that port and then
re-installing the latest version of the software from our website here
because the version on the microsoft app store is outdated:

http://SGWSniper.com

The installation steps are simple, you basically just double click the
installer, but please read the README.txt for full installation notes!

and then use the following coupon code to activate your license again:

KSUOGI2U

After that your software and license should be successfully activated!

**Comment by Auction-Sniper** [comment]
Please be sure to uninstall the version from the microsoft windows app
store because that has errors as you can see...

Please let us know if we can be of further assistance!

Thank you,
Customer Service
