### ISSUE TITLE
Installment Error

### ISSUE THREAD

**Issue by akhumdingers** [Auction-Sniper/sniping#2]
When I tried drag the install file to the command prompt it wont install. The error is permission denied. 
![image](https://github.com/Auction-Sniper/sniping/assets/145206742/80758eee-16af-4e5d-a6c0-717aba91f3ca)

**Comment by Auction-Sniper** [comment]
Hi on windows it's just double click the installer to execute it on Mac
it's drag and drop into terminal, also please leave the download folder
structure intact, don't manually copy and paste folder into program files
as your screenshot shows because the installer automatically puts it in the
correct folders for you so please delete that folder in your program files
and redownload and reextract and reinstall the app again
