### ISSUE TITLE
Bids not being placed.

### ISSUE THREAD

**Issue by akhumdingers** [Auction-Sniper/sniping#3]
Having an issue where sometimes a bid is placed but not others. If you can see the screenshot, it says the auction was sniped but in the bid history there was never anything put in. This was after a computer restart and was the first bid placed in there. Is this something I can fix?
![Failed bid](https://github.com/Auction-Sniper/sniping/assets/145206742/c4a1f05b-90ef-4013-95d0-a561b7eb5ef9)

**Comment by Auction-Sniper** [comment]
Hi akhumdingers,

Yes, there are settings you can change to increase chances of winning a snipe auction by going to the top menu and increasing the snipe timing to a greater number lets says for example 10 seconds, especially if you have a slow connection or are outside the US as your connection will be slow and need the extra time, but just because it says sniped doesn't mean you successfully sniped, because you may have been outbid on that auction and it will still say sniped, because it just lets you know that it did attempt to snipe that auction, but whether you win that auction or not depends on other factors so just please ensure those other factors are checked and also please try leaving the program running plenty of time before the auction as in don't start the program 1 minute before the auction ends hoping to snipe successfully, think of the sniping software as a tool that places bids for you last seconds, but you still have to ensure other factors on your side are good too...

Hope that helps,

Please let us know if we can be of further assistance.

Thank you,
Customer Service
