### ISSUE TITLE
Lost all my future snipes

### ISSUE THREAD

**Issue by duartef509** [Auction-Sniper/sniping#4]
I had some snipes ready for next couple days now they are gone. Not sure what happen. Do I loose all the snipes if I close the computer?

No sure what happen but now i have to redo all of them!

Can you help me with this

Thank Youi
Duarte

**Comment by Auction-Sniper** [comment]
Hi Duarte,

Have you tried logging into your account through the app on the ShopGoodwill website? You must be logged in for your snipes to show.

Generally speaking, it is recommended to refrain from closing the app or restarting your computer once you have your snipes all loaded, that will prevent any disruptions from occurring, so try to leave the app running in your system tray by closing the main window instead of quitting and that will minimize it to the system tray to run in the background.

Other than that, no, simply closing the program shouldn't remove your snipes, the only way your snipes could have been removed is if you deleted your google chrome cache or deleted the sniper profile folder which I don't believe you did so, I believe you might just be logged out of your account and wondering why your snipes aren't loading.

Anyhow, I hope that helps solve your issue. Please feel free to let us know if you need further assistance. Thank you!

Customer Service

**Comment by duartef509** [comment]
Thank you for the fast response, I might have cleared the cache on Google
Chrome, but now I know not to do that.

Duarte
