### ISSUE TITLE
Different Account

### ISSUE THREAD

**Issue by TimDeutscher** [Auction-Sniper/sniping#5]
Hello, 
I had to change my account that I was using the sniper bot on and now I am prompted to pay for the application again. I can not use my previous username and account on the website because I was banned from placing bids under that account. I've since made a new account and was wondering if there is a way to transfer it to my new account and remove the old one. 
Thank you

**Comment by Auction-Sniper** [comment]
Hi Tim,

Since we charge only a one-time fee, we charge per device/user, so if it's prompting you to pay again, it's either because you're using it on a whole new device, or you logged into a whole new user account on your computer, the license is NOT tied to your online account, it is tied to your computer/userprofile, however since your purchase was made fairly recent and there is no way for us to verify if you're still using it on another computer account, unfortunately, we won't be able to transfer your license or give you a free license however we can offer you a limited time 5% discount you can use below:

Discount Code: CADVP3F5
Expires: Oct. 25

Please let us know if we can be of further assistance.

Best Regards,
Customer Service

**Comment by TimDeutscher** [comment]
That makes sense. I'm not sure what the problem is now but I get the following error: 

Unhandled Error
Error: listen EADDRINUSE: address already in use 127.0.0.1:54645
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_uvExceptionWithHostPort (node:internal/errors:589:12)
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at doListen (node:net:1937:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

Hopefully you can tell me how to fix this. 
Thank You
