### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by TimDeutscher** [Auction-Sniper/sniping#6]
Hello, thank you for your response, it made sense. Now I have the following error: 
Unhandled Error
Error: listen EADDRINUSE: address already in use 127.0.0.1:54645
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_uvExceptionWithHostPort (node:internal/errors:589:12)
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at doListen (node:net:1937:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

Please let me know if there is anything I can do. 
Thank You

**Comment by Auction-Sniper** [comment]
Hi Tim,

That error occurs when you open and close the program more than once from an old version that you are using, please first reboot your computer to free up the error, then proceed to update to the latest version directly from our website here:

http://SGWSniper.com

You can also find an installation tutorial video here if you don't already know how to install it, basically you simply extract the downloaded zip archive and then double click the installer file within it for Windows and on Mac drag-and-drop to terminal:

https://www.youtube.com/watch?v=Bee4D1jd3E4

Please also note, during activation disable your windows firewall before you launch the program otherwise it may block your activation, then after activation you can enable your firewall again.

Please let is know if we can be of further assistance.

Best regards,
Customer Service

**Comment by TimDeutscher** [comment]
Thank you very much, that fixed it. Have a nice day.
